enable:
  issues: true
  prs: true

labels:
  '🎸 Chore':
    - '^\[Chore(?:\/#[0-9]+)?\]'
  '🔗 CI/CD':
    - '^\[Ci(?:\/#[0-9]+)?\]'
  '🎨 Design':
    - '^\[Design(?:\/#[0-9]+)?\]'
  '📃 Docs':
    - '^\[Docs(?:\/#[0-9]+)?\]'
  '⭐ Feature':
    - '^\[Feat(?:\/#[0-9]+)?\]'
  '🔧 Fix':
    - '^\[Fix(?:\/#[0-9]+)?\]'
  '🪄 Refactor':
    - '^\[Refactor(?:\/#[0-9]+)?\]'
  '⚙️ Setting':
    - '^\[Setting(?:\/#[0-9]+)?\]'
  '🌈 Deploy':
    - '^\[Deploy(?:\/#[0-9]+)?\]'
  '🧩 Test':
    - '^\[Test(?:\/#[0-9]+)?\]'
  '⚠️ HOTFIX':
    - '^\[HOTFIX(?:\/#[0-9]+)?\]'
