name: PR and Issue Labeler

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on title prefix
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign PR/Issue to yourself
        uses: actions/github-script@v7
        with:
          script: |
            const assignee = 'hansoojeongsj'; 
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [assignee],
            });
